#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-freetype_py
Version  : 2.4.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/a7/6d/66c222fae5dc5fd13fd840ab75feb49f78963f560a56e134c85f1236a94c/freetype-py-2.4.0.zip
Source0  : https://files.pythonhosted.org/packages/a7/6d/66c222fae5dc5fd13fd840ab75feb49f78963f560a56e134c85f1236a94c/freetype-py-2.4.0.zip
Summary  : Freetype python bindings
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-freetype_py-license = %{version}-%{release}
Requires: pypi-freetype_py-python = %{version}-%{release}
Requires: pypi-freetype_py-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(certifi)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
FreeType (high-level Python API)
================================
Freetype Python provides bindings for the FreeType library. Only the
high-level API is bound.

%package license
Summary: license components for the pypi-freetype_py package.
Group: Default

%description license
license components for the pypi-freetype_py package.


%package python
Summary: python components for the pypi-freetype_py package.
Group: Default
Requires: pypi-freetype_py-python3 = %{version}-%{release}

%description python
python components for the pypi-freetype_py package.


%package python3
Summary: python3 components for the pypi-freetype_py package.
Group: Default
Requires: python3-core
Provides: pypi(freetype_py)

%description python3
python3 components for the pypi-freetype_py package.


%prep
%setup -q -n freetype-py-2.4.0
cd %{_builddir}/freetype-py-2.4.0
pushd ..
cp -a freetype-py-2.4.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683302420
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-freetype_py
cp %{_builddir}/freetype-py-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-freetype_py/c8dfd114e52b58147db0b645e40d629c5de6a325 || :
cp %{_builddir}/freetype-py-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/pypi-freetype_py/aec9b895cb0c809a06b654eb2a0f490bbc220a86 || :
cp %{_builddir}/freetype-py-%{version}/doc/license.rst %{buildroot}/usr/share/package-licenses/pypi-freetype_py/81415a4051344e16940a670ff92996fd69844907 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-freetype_py/81415a4051344e16940a670ff92996fd69844907
/usr/share/package-licenses/pypi-freetype_py/aec9b895cb0c809a06b654eb2a0f490bbc220a86
/usr/share/package-licenses/pypi-freetype_py/c8dfd114e52b58147db0b645e40d629c5de6a325

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
